/**
 * A Call of Cthulhu character for editor tests: the blank built-in template,
 * which the server accepts as it stands, with the parts under test overridden.
 */

import type { Character } from '../../../../types';

export const COC_BLANK_SHEET: Record<string, unknown> = {
  investigatorName: "Blank Investigator",
  occupation: "Investigator",
  era: "Modern",
  characteristics: {
    "STR": {"regular": 50, "half": 25, "fifth": 10},
    "CON": {"regular": 50, "half": 25, "fifth": 10},
    "SIZ": {"regular": 50, "half": 25, "fifth": 10},
    "DEX": {"regular": 50, "half": 25, "fifth": 10},
    "APP": {"regular": 50, "half": 25, "fifth": 10},
    "INT": {"regular": 50, "half": 25, "fifth": 10},
    "POW": {"regular": 50, "half": 25, "fifth": 10},
    "EDU": {"regular": 50, "half": 25, "fifth": 10},
  },
  derivedStats: {
    "hp": {"maximum": 10, "current": 10, "formula": "(CON+SIZ)/10", "majorWoundThreshold": 1},
    "magicPoints": {"maximum": 10, "current": 10, "formula": "POW/5"},
    "sanity": {"starting": 50, "current": 50, "maximum": 99, "formula": "POW"},
    "luck": {"score": 50, "notes": ""},
    "moveRate": 8,
    "build": 0,
    "damageBonus": "0",
    "dodge": {"value": 25, "formula": "DEX/2", "improvementChecked": false},
  },
  skills: {
    "accounting": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "anthropology": {"baseValue": 1, "currentValue": 1, "improvementChecked": false},
    "appraise": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "archaeology": {"baseValue": 1, "currentValue": 1, "improvementChecked": false},
    "libraryUse": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "occult": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "spotHidden": {"baseValue": 25, "currentValue": 25, "improvementChecked": false},
    "listen": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "naturalWorld": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "charm": {"baseValue": 15, "currentValue": 15, "improvementChecked": false},
    "fastTalk": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "intimidate": {"baseValue": 15, "currentValue": 15, "improvementChecked": false},
    "persuade": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "psychology": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "climb": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "jump": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "swim": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "throw": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "stealth": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "dodge": {"baseValue": 25, "currentValue": 25, "improvementChecked": false},
    "fighting": {"brawl": {"baseValue": 25, "currentValue": 25, "improvementChecked": false}, "custom": []},
    "firearms": {"handgun": {"baseValue": 20, "currentValue": 20, "improvementChecked": false}, "rifle": {"baseValue": 25, "currentValue": 25, "improvementChecked": false}, "shotgun": {"baseValue": 25, "currentValue": 25, "improvementChecked": false}, "custom": []},
    "artCraft": {"baseValue": 5, "currentValue": 5, "improvementChecked": false, "specialization": null},
    "disguise": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "driveAuto": {"baseValue": 20, "currentValue": 20, "improvementChecked": false},
    "firstAid": {"baseValue": 30, "currentValue": 30, "improvementChecked": false},
    "locksmith": {"baseValue": 1, "currentValue": 1, "improvementChecked": false},
    "mechanicalRepair": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "electricalRepair": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "operateHeavyMachinery": {"baseValue": 1, "currentValue": 1, "improvementChecked": false},
    "sleightOfHand": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "pilot": {"baseValue": 1, "currentValue": 1, "improvementChecked": false, "specialization": null},
    "history": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "languageOwn": {"baseValue": 50, "currentValue": 50, "improvementChecked": false, "language": "English"},
    "languageOther": [],
    "law": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "medicine": {"baseValue": 1, "currentValue": 1, "improvementChecked": false},
    "science": [],
    "navigate": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "survival": {"baseValue": 10, "currentValue": 10, "improvementChecked": false, "specialization": null},
    "track": {"baseValue": 10, "currentValue": 10, "improvementChecked": false},
    "creditRating": {"baseValue": 0, "currentValue": 0, "improvementChecked": false},
    "cthulhuMythos": {"baseValue": 0, "currentValue": 0, "improvementChecked": false},
    "psychoanalysis": {"baseValue": 1, "currentValue": 1, "improvementChecked": false},
    "ride": {"baseValue": 5, "currentValue": 5, "improvementChecked": false},
    "customSkills": [],
  },
  combat: {"weapons": []},
  wealth: {"spendingLevel": "Average", "cash": 0, "assets": "", "notes": ""},
  possessions: [],
  backstory: {
    "description": "",
    "personalDescription": "",
    "ideology": "",
    "significantPeople": "",
    "meaningfulLocations": "",
    "treasuredPossessions": "",
    "traits": "",
    "injuriesAndScars": "",
    "phobiasAndManias": "",
    "arcaneTomesAndSpells": "",
    "encountersWithStrangeEntities": "",
  },
};

export function cocCharacter(overrides: Record<string, unknown> = {}): Character {
  const data: Record<string, unknown> = JSON.parse(JSON.stringify(COC_BLANK_SHEET));
  return {
    id: 'char-1',
    userId: 'user-1',
    name: 'Investigator',
    gameSystem: 'CALL_OF_CTHULHU_7E',
    campaignId: null,
    tokenImageUrl: null,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    data: { ...data, ...overrides },
  } as unknown as Character;
}
